%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/umarchughtai/Downloads/access_time-2.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/02 00:01:34
clc
clear all
close all
%% Initialize variables.
filename = '/Users/umarchughtai/Downloads/access_time-2.txt';
delimiter = '\t';
startRow = 11;
endRow = 11;

startRow2 = 14;
endRow2 = 14;

startRow3 = 18;
endRow3 = 18;

startRow4 = 21;
endRow4 = 21;

startRow5 = 25;
endRow5 = 25;

startRow6 = 28;
endRow6 = 28;

%% Format for each line of text:
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read SDRAM to onchip

textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);
%% Read SDRAM to SRAM transfer data

fileID = fopen(filename,'r');
textscan(fileID, '%[^\n\r]', startRow2-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray2 = textscan(fileID, formatSpec, endRow2-startRow2+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);
%% Read Onchip to SDRAM transfer data

fileID = fopen(filename,'r');
textscan(fileID, '%[^\n\r]', startRow3-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray3 = textscan(fileID, formatSpec, endRow3-startRow3+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

%% Read Onchip to SRAM transfer data

fileID = fopen(filename,'r');
textscan(fileID, '%[^\n\r]', startRow4-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray4 = textscan(fileID, formatSpec, endRow4-startRow4+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

%% Read SRAM to SDRAM transfer data

fileID = fopen(filename,'r');
textscan(fileID, '%[^\n\r]', startRow5-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray5 = textscan(fileID, formatSpec, endRow5-startRow5+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);

%% Read SRAM to Onchip transfer data

fileID = fopen(filename,'r');
textscan(fileID, '%[^\n\r]', startRow6-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray6 = textscan(fileID, formatSpec, endRow6-startRow6+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');
fclose(fileID);
%% Allocate imported array to column variable names

x = (dataArray(1,1:512)); % sdram to onchip
x2 = (dataArray2(1,1:512)); % sdram to sram
x3 = (dataArray3(1,1:512)); % Onchip to SDRAM
x4 = (dataArray4(1,1:512)); % Onchip to SRAM
x5 = (dataArray5(1,1:512)); % SRAM to SDRAM
x6 = (dataArray6(1,1:512)); % SRAM to Onchip
x = cell2mat(x);
x2 = cell2mat(x2);
x3 = cell2mat(x3);
x4 = cell2mat(x4);
x5 = cell2mat(x5);
x6 = cell2mat(x6);
%hold all
%figure(1)
subplot(2,3,1)
plot(x,'-o')
xlim([0 520])
ylim([0 1100])
title('SDRAM to Onchip')
xlabel('bits')
ylabel('Transfer time \mu S')
subplot(2,3,4)
plot(x2,'-o')
xlim([0 520])
ylim([0 1100])
title('SDRAM to SRAM')
xlabel('bits')
ylabel('Transfer time \mu S')
subplot(2,3,2)
plot(x3,'-o')
xlim([0 520])
ylim([0 1100])
title('Onchip to SDRAM')
xlabel('bits')
ylabel('Transfer time \mu S')
subplot(2,3,5)
plot(x4,'-o')
xlim([0 520])
ylim([0 1100])
title('Onchip to SRAM')
xlabel('bits')
ylabel('Transfer time \mu S')
subplot(2,3,3)
plot(x5,'-o')
xlim([0 520])
ylim([0 1100])
title('SRAM to SDRAM')
xlabel('bits')
ylabel('Transfer time \mu S')
subplot(2,3,6)
plot(x6,'-o')
xlim([0 520])
ylim([0 1100])
title('SRAM to Onchip')
xlabel('bits')
ylabel('Transfer time \mu S')
% 
% figure(2)
% plot(x2,'-o')
% xlim([0 520])
% ylim([0 1100])
% title('SDRAM to SRAM')
% xlabel('bits')
% ylabel('Transfer time \mu S')
% 
% figure(3)
% plot(x3,'-o')
% xlim([0 520])
% ylim([0 1100])
% title('Onchip to SDRAM')
% xlabel('bits')
% ylabel('Transfer time \mu S')
% 
% figure(4)
% plot(x4,'-o')
% xlim([0 520])
% ylim([0 1100])
% title('Onchip to SRAM')
% xlabel('bits')
% ylabel('Transfer time \mu S')
% 
% figure(5)
% plot(x5,'-o')
% xlim([0 520])
% ylim([0 1100])
% title('SRAM to SDRAM')
% xlabel('bits')
% ylabel('Transfer time \mu S')
% 
% figure(6)
% plot(x6,'-o')
% xlim([0 520])
% ylim([0 1100])
% title('SRAM to Onchip')
% xlabel('bits')
% ylabel('Transfer time \mu S')
%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;